### ISSUE TITLE
使用 1.0.0-beta.2 报错

### ISSUE THREAD

**Issue by javmain** [eyelly-wu/taro-echarts#1]
TypeError: Cannot read property 'forEach' of undefined

使用时提示这个错误

**Comment by javmain** [comment]
把你封装的组件放到本地，从 echarts 下载最新版本的，没有出现上面的报错，难道是 echarts 的锅？

**Comment by eyelly-wu** [comment]
@javmain 在发布1.0.0-beta.2之前，在示例项目中是使用link的方式来使用组件的，示例项目可以正常跑，不过我还没试过通过install来跑示例项目

**Comment by javmain** [comment]
嗯，我使用的 install 方式跑的项目。

**Comment by eyelly-wu** [comment]
@javmain 我install后也可以正常跑的，看一下你的taro info信息，我的taro是v1.2.26

**Comment by javmain** [comment]
使用的是 taro 的最新版本 1.3.0。但是我把你封装的组件拷贝到 src/components 目录下，然后在 page 页引用，可以运行正常。

**Comment by eyelly-wu** [comment]
@javmain 升到1.3.0的确会报如下错误，看样子是与Hooks API有关，后期我会调整代码
![image](https://user-images.githubusercontent.com/24505069/59485938-4bdefc00-8eaa-11e9-9727-9b4747ba4eb7.png)

**Comment by javmain** [comment]
收到。

**Comment by eyelly-wu** [comment]
@javmain 代码已调整，我这测试ok了

**Comment by javmain** [comment]
@eyelly-wu nice。运行正常。非常感谢。
