### ISSUE TITLE
不支持taro next

### ISSUE THREAD

**Issue by yz1311** [eyelly-wu/taro-echarts#8]
**问题描述**
不支持taro next

**复现步骤**
[复现问题的步骤]

**期望行为**
运行正常

**报错信息**

![image](https://user-images.githubusercontent.com/9854019/78206916-b6613700-74d2-11ea-87b8-4d6bbbc8ea05.png)

**系统信息**
Taro CLI 3.0.0-beta.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.2 => 3.0.0-beta.2 
      @tarojs/taro: 3.0.0-beta.2 => 3.0.0-beta.2 
      @tarojs/webpack-runner: 3.0.0-beta.2 => 3.0.0-beta.2 
      eslint-config-taro: 3.0.0-beta.2 => 3.0.0-beta.2 
      react: ^16.10.0 => 16.13.0 
    npmGlobalPackages:
      typescript: 3.7.5

**补充信息**
Chart/index.js 因为react的引用问题已经改了
```
import React, {Component} from 'react';
import Taro from '@tarojs/taro'
```
上面的报错是改了之后的报出的

**Comment by BinZhiZhu** [comment]
我升级了taro next也的确是同样的报错 2.x是正常

**Comment by yz1311** [comment]
@BinZhiZhu 
推荐使用 https://github.com/elvinzhu/techarts ，直接用taro写的，没有引用原生组件那些麻烦事

**Comment by BinZhiZhu** [comment]
> @BinZhiZhu 
> 
> 推荐使用 https://github.com/elvinzhu/techarts ，直接用taro写的，没有引用原生组件那些麻烦事

可以 我真准备不直接依赖taro 谢谢老哥
